### ISSUE TITLE
Does not build with GCC 6.3

### ISSUE THREAD

**Issue by Bu11etmagnet** [goldsborough/lru-cache#10]
```
../include/lru/cache.hpp:192:42: error: throw will always call terminate() [-Werror=terminate]
       throw LRU::Error::EmptyCache("back");
                                          ^

```

How can you put a `throw` into a function marked `noexcept` ?
